#!/usr/bin/env bash
# smoke-native.sh <path-to-sumchain-binary> <40-hex commit>
#
# Runs a native release binary directly on this machine as a one-validator
# NONPRODUCTION devnet (chain id 1337, a key generated by the binary itself in
# a temp directory, never printed), with health bound to LOOPBACK, and requires:
#   * `sumchain --version` prints "sumchain <commit>";
#   * no shared library is missing (ldd);
#   * GET /health -> 200, GET /ready -> 200 after a block, and /metrics passes
#     tools/lane-b/wave1-monitor.sh verify (all nine Wave 1 subsystems, two
#     bounded labels);
#   * SIGTERM -- systemd's default stop signal -- ends it with exit status 0
#     and "Node shutdown complete", and the database reopens immediately.
# Everything it creates is removed on every exit path.
set -euo pipefail
[[ $# -eq 2 ]] || { echo "usage: smoke-native.sh <sumchain binary> <commit>" >&2; exit 2; }
BIN=$(cd "$(dirname "$1")" && pwd)/$(basename "$1") COMMIT=$2
HERE=$(cd "$(dirname "$0")" && pwd)
T=$(mktemp -d); PID=""
cleanup() { [[ -n $PID ]] && kill -KILL "$PID" 2>/dev/null; rm -rf "$T"; }
trap cleanup EXIT
fail() { echo "SMOKE FAIL: $*" >&2; [[ -f $T/node.log ]] && tail -30 "$T/node.log" >&2; exit 1; }

ver=$("$BIN" --version) || fail "--version failed"
[[ $ver == "sumchain $COMMIT" ]] || fail "the binary reports '$ver', not 'sumchain $COMMIT'"
if command -v ldd >/dev/null && ldd "$BIN" 2>&1 | grep -q 'not found'; then
  fail "missing shared libraries: $(ldd "$BIN" | grep 'not found' | tr '\n' ' ')"
fi
echo "ok   --version: $ver"

port() { python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1",0)); print(s.getsockname()[1])'; }
P2P=$(port) RPC=$(port) HP=$(port)
pk=$("$BIN" keygen --output "$T/fixture-validator.json" | sed -n 's/^Public key: //p')
[[ -n $pk ]] || fail "keygen printed no public key"
cat > "$T/genesis.json" <<EOF
{"chain_id":1337,"genesis_time":$(date +%s)000,"validators":["$pk"],"alloc":{},
 "params":{"block_time_ms":1000,"max_block_bytes":1000000,"max_txs_per_block":1000,"min_fee":1}}
EOF
cat > "$T/node.toml" <<EOF
[node]
genesis = "$T/genesis.json"
data_dir = "$T/data"
validator_key = "$T/fixture-validator.json"
[consensus]
engine = "poa"
[network]
listen_addr = "/ip4/127.0.0.1/tcp/$P2P"
mdns = false
[rpc]
addr = "127.0.0.1:$RPC"
[health]
addr = "127.0.0.1:$HP"
[logging]
level = "info"
json = false
EOF
NO_COLOR=1 "$BIN" run --config "$T/node.toml" > "$T/node.log" 2>&1 &
PID=$!

code() { curl -s -o /dev/null -w '%{http_code}' --max-time 3 "http://127.0.0.1:$HP$1" || true; }
wait_for() {  # path, want, seconds
  local i
  for ((i = 0; i < $3; i++)); do
    [[ $(code "$1") == "$2" ]] && return 0
    kill -0 "$PID" 2>/dev/null || fail "the node exited"
    sleep 1
  done
  fail "GET $1 did not return $2 within $3 s (last: $(code "$1"))"
}
wait_for /health 200 60; echo "ok   GET /health  -> 200"
wait_for /ready 200 90;  echo "ok   GET /ready   -> 200 (a block past genesis exists)"
[[ $(code /metrics) == 200 ]] || fail "GET /metrics -> $(code /metrics)"
bash "$HERE/../lane-b/wave1-monitor.sh" verify "http://127.0.0.1:$HP" >/dev/null || fail "wave1-monitor.sh verify failed"
echo "ok   /metrics complete (wave1-monitor verify)"

kill -TERM "$PID"
for ((i = 0; i < 300; i++)); do kill -0 "$PID" 2>/dev/null || break; sleep 0.1; done
kill -0 "$PID" 2>/dev/null && fail "SIGTERM did not stop the node within 30 s"
set +e; wait "$PID"; rc=$?; set -e; PID=""
[[ $rc -eq 0 ]] || fail "SIGTERM: exit status $rc, want 0"
grep -q 'Node shutdown complete' "$T/node.log" || fail "SIGTERM did not complete the shutdown sequence"
"$BIN" info --data-dir "$T/data" > "$T/info.txt" 2>&1 || fail "the database did not reopen after SIGTERM: $(tail -3 "$T/info.txt")"
grep -q 'Latest height:' "$T/info.txt" || fail "the reopened database holds no chain"
echo "ok   SIGTERM -> exit 0, shutdown complete, database reopened"
echo "SMOKE OK: $BIN ($ver)"
