//! SIGTERM and SIGINT both stop the node gracefully; SIGKILL stays distinguishable.
//!
//! Each test runs the real `sumchain` binary as a one-validator NONPRODUCTION
//! devnet (chain id 1337, a key generated by the binary itself into a temp
//! directory), waits until it has produced a block, signals it, and then
//! requires:
//!   * SIGTERM / SIGINT: exit status 0, the whole shutdown sequence in the log
//!     ("Shutdown signal received (<signal>)" through "Node shutdown complete"),
//!     and the database reopening IMMEDIATELY afterwards (`sumchain info` opens
//!     it, which fails while another process holds RocksDB's LOCK);
//!   * SIGKILL: terminated by signal 9, with no "Node shutdown complete" -- a
//!     forced stop never looks like a clean one.
//!
//! SIGTERM is what systemd sends to stop a unit (its default KillSignal), and
//! what Docker and Kubernetes send. Handling it is what makes a custom
//! `KillSignal=SIGINT` unnecessary.
#![cfg(unix)]

use std::fs;
use std::io::Read;
use std::net::TcpListener;
use std::os::unix::process::ExitStatusExt;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, ExitStatus, Stdio};
use std::time::{Duration, Instant};

const BIN: &str = env!("CARGO_BIN_EXE_sumchain");

fn free_port() -> u16 {
    TcpListener::bind("127.0.0.1:0")
        .unwrap()
        .local_addr()
        .unwrap()
        .port()
}

struct Devnet {
    dir: tempfile::TempDir,
    log: PathBuf,
    child: Child,
}

impl Devnet {
    fn data(&self) -> PathBuf {
        self.dir.path().join("data")
    }

    fn log_text(&self) -> String {
        let mut s = String::new();
        if let Ok(mut f) = fs::File::open(&self.log) {
            let _ = f.read_to_string(&mut s);
        }
        s
    }
}

impl Drop for Devnet {
    fn drop(&mut self) {
        let _ = self.child.kill();
        let _ = self.child.wait();
    }
}

fn start() -> Devnet {
    let dir = tempfile::tempdir().unwrap();
    let p = dir.path();
    let key = p.join("fixture-validator.json");
    let out = Command::new(BIN)
        .args(["keygen", "--output"])
        .arg(&key)
        .output()
        .unwrap();
    assert!(out.status.success(), "keygen failed: {out:?}");
    let pk = String::from_utf8_lossy(&out.stdout)
        .lines()
        .find_map(|l| l.strip_prefix("Public key: ").map(str::to_owned))
        .expect("keygen prints the public key");
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_millis();
    fs::write(
        p.join("genesis.json"),
        format!(
            r#"{{"chain_id":1337,"genesis_time":{now},"validators":["{pk}"],"alloc":{{}},
 "params":{{"block_time_ms":1000,"max_block_bytes":1000000,"max_txs_per_block":1000,"min_fee":1}}}}"#
        ),
    )
    .unwrap();
    fs::write(
        p.join("node.toml"),
        format!(
            r#"[node]
genesis = "{g}"
data_dir = "{d}"
validator_key = "{k}"
[consensus]
engine = "poa"
[network]
listen_addr = "/ip4/127.0.0.1/tcp/{p2p}"
mdns = false
[rpc]
addr = "127.0.0.1:{rpc}"
[health]
addr = "127.0.0.1:{health}"
[logging]
level = "info"
json = false
"#,
            g = p.join("genesis.json").display(),
            d = p.join("data").display(),
            k = key.display(),
            p2p = free_port(),
            rpc = free_port(),
            health = free_port(),
        ),
    )
    .unwrap();
    let log = p.join("node.log");
    let f = fs::File::create(&log).unwrap();
    let child = Command::new(BIN)
        .args(["run", "--config"])
        .arg(p.join("node.toml"))
        .env("NO_COLOR", "1")
        .stdout(Stdio::from(f.try_clone().unwrap()))
        .stderr(Stdio::from(f))
        .spawn()
        .unwrap();
    let net = Devnet { dir, log, child };
    wait_for(&net, "Produced block", Duration::from_secs(60));
    net
}

fn wait_for(net: &Devnet, needle: &str, within: Duration) {
    let t = Instant::now();
    while t.elapsed() < within {
        if net.log_text().contains(needle) {
            return;
        }
        std::thread::sleep(Duration::from_millis(200));
    }
    panic!("no {needle:?} within {within:?}; log:\n{}", net.log_text());
}

fn signal(net: &Devnet, sig: &str) {
    let st = Command::new("kill")
        .arg(format!("-{sig}"))
        .arg(net.child.id().to_string())
        .status()
        .unwrap();
    assert!(st.success(), "kill -{sig} failed");
}

fn wait_exit(net: &mut Devnet, within: Duration) -> ExitStatus {
    let t = Instant::now();
    loop {
        if let Some(st) = net.child.try_wait().unwrap() {
            return st;
        }
        assert!(
            t.elapsed() < within,
            "the node did not exit within {within:?}; log:\n{}",
            net.log_text()
        );
        std::thread::sleep(Duration::from_millis(100));
    }
}

/// Opens the database the way any later process would. RocksDB refuses while
/// another process holds its LOCK, so success proves the lock was released.
fn reopen(data: &Path) -> std::process::Output {
    Command::new(BIN)
        .args(["info", "--data-dir"])
        .arg(data)
        .env("NO_COLOR", "1")
        .output()
        .unwrap()
}

fn graceful(sig: &str) {
    let mut net = start();
    signal(&net, sig);
    let st = wait_exit(&mut net, Duration::from_secs(30));
    let log = net.log_text();
    assert!(
        st.success(),
        "{sig}: exit status {st:?}, want 0; log:\n{log}"
    );
    assert!(
        log.contains(&format!("Shutdown signal received (SIG{sig})")),
        "{sig} did not reach the shutdown path:\n{log}"
    );
    for step in [
        "Stopping consensus engine",
        "Stopping RPC and health servers",
        "Flushing database",
        "Node shutdown complete",
    ] {
        assert!(
            log.contains(step),
            "{sig}: the shutdown sequence skipped {step:?}:\n{log}"
        );
    }
    let out = reopen(&net.data());
    let text =
        String::from_utf8_lossy(&out.stdout).to_string() + &String::from_utf8_lossy(&out.stderr);
    assert!(
        out.status.success(),
        "{sig}: the database did not reopen immediately: {text}"
    );
    assert!(
        text.contains("Latest height:"),
        "{sig}: reopened database holds no chain: {text}"
    );
}

#[test]
fn sigterm_stops_the_node_gracefully_and_releases_the_database() {
    graceful("TERM");
}

#[test]
fn sigint_still_stops_the_node_gracefully() {
    graceful("INT");
}

#[test]
fn sigkill_is_distinguishable_from_a_clean_stop() {
    let mut net = start();
    signal(&net, "KILL");
    let st = wait_exit(&mut net, Duration::from_secs(10));
    assert!(!st.success(), "a SIGKILL must not look like a clean exit");
    assert_eq!(
        st.signal(),
        Some(9),
        "want termination by signal 9, got {st:?}"
    );
    assert!(
        !net.log_text().contains("Node shutdown complete"),
        "a killed node logged a clean shutdown"
    );
}
