#!/usr/bin/env bash
# Genuine per-candidate Stage-5 terminal-verifier + mutation harness (docs/b0-pre/venue/VENUE.md §3.4).
#
# SCOPE (be precise about what is executed vs venue-only):
#   * It performs GENUINE verification of, and the five required MUTATIONS over, a
#     genuine terminal proof/receipt fixture, INSIDE the pinned container, deriving
#     each mutation's rejection from the ACTUAL verifier result.
#   * The fixture is GENERATED by proving the OFFICIAL candidate guest with the pinned
#     prover toolchain (prove_fixture.sh, provider-neutral) — the command path is
#     IMPLEMENTED but VENUE-UNEXECUTED: the candidate guests now carry official guest
#     SOURCE (routing through b0-pre-guest-core), so prove_fixture.sh locates/builds the
#     real guest, but generation still fails closed off-venue (no pinned toolchain /
#     container / native builder). Because no venue-built guest identity exists yet, any
#     fixture it eventually proves is STILL self-labeled NON_SELECTION /
#     NOT_AN_OFFICIAL_GUEST (four stamps). An externally supplied genuine fixture
#     (SP1_G16_FIXTURE / RISC0_G16_FIXTURE, from an authorized partner venue) OVERRIDES
#     generation. A synthetic fixture is NEVER substituted.
#   * NOT authoritative-ready while proof/receipt generation is venue-unexecuted.
#
# Invoked by `produce_stage5` in run_authoritative.sh with:
#   env:  VERIFIER_REF  the pinned builder image the verifier runs INSIDE
#         OUT_DIR       a clean scratch dir for THIS (candidate, arch) Stage-5 run
#         CMD_LOG       the command-log file the exact in-container commands append to
#         SCHEMA_ARCH   X86_64 | Aarch64 (schema-cased arch)
#   args: <candidate_lc> <arch>   candidate_lc in {sp1, risc0}; arch in {x86_64, aarch64}
#
# Writes into $OUT_DIR (all bound BY HASH into the Stage-5 record):
#   mutations.json   [{name,actual_rejected}] for EXACTLY the five required cases,
#                    each `actual_rejected` DERIVED from the OBSERVED verifier result;
#   fixtures.json    [{label,path}] of the RAW artifacts the run is bound to — the
#                    exact genuine fixture bytes, the in-container-generated runner
#                    Cargo.lock, the terminal proof/receipt, the consumed verifier
#                    material (vk / control root), and the public output;
# and appends to $CMD_LOG (bound via command_log_blake3_hex): the exact docker
# commands, the runner lock BLAKE3, the verifier-material manifest identity, and each
# raw-artifact BLAKE3. `venue-verify stage5-generate` then hashes every raw artifact
# into `fixture_hashes`, binds the record to candidate/arch/container-digest/
# source-commit/tool-identity/commands, and DERIVES overall_pass from mutations.json —
# so a non-rejecting mutation yields NO passing Stage-5 record and this harness never
# decides the pass.
#
# FAIL CLOSED, never fabricate: a missing tool (docker/python3/b3sum), a missing
# genuine fixture, a missing verifier-material manifest, a missing/broken toolchain, or
# a verifier that does not reproduce stops the run non-zero and writes NO
# fixtures.json/mutations.json. TEST_ONLY / synthetic evidence must NEVER reach this
# authoritative path: the harness refuses the off-venue dry-run mode, and the genuine
# fixture must be self-labeled non-selection (all four stamps). The genuine
# in-container verifier execution runs ONLY on a native Linux + Docker venue; it is
# expected to fail closed off-venue — the off-venue CONTRACT is what is unit-tested.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib.sh
. "$HERE/lib.sh"

# The four required non-selection stamps a genuine fixture MUST carry so its guest
# identity can never be mistaken for official evidence (mirrors b0_pre_vmat::
# REQUIRED_STAMPS and the candidate contract fixtures). A fixture missing any one is
# refused — an "authoritative-looking" fixture is never accepted or fabricated.
REQUIRED_STAMPS='["TEST_ONLY","NON_SELECTION","INVALID_FOR_R0","NOT_AN_OFFICIAL_GUEST"]'

CAND_LC="${1:-}"
ARCH="${2:-}"
case "$CAND_LC" in
  sp1|risc0) ;;
  *) die "candidate must be sp1|risc0 (got '${CAND_LC:-}')" ;;
esac
case "$ARCH" in
  x86_64|aarch64) ;;
  *) die "arch must be x86_64|aarch64 (got '${ARCH:-}')" ;;
esac

# Required binding env from produce_stage5 (each empty value fails closed).
[ -n "${VERIFIER_REF:-}" ] || die "VERIFIER_REF (pinned builder image the verifier runs inside) is required"
[ -n "${OUT_DIR:-}" ]      || die "OUT_DIR (Stage-5 scratch output dir) is required"
[ -n "${CMD_LOG:-}" ]      || die "CMD_LOG (command-log file to bind the run to) is required"
[ -n "${SCHEMA_ARCH:-}" ]  || die "SCHEMA_ARCH (X86_64|Aarch64) is required"
case "$SCHEMA_ARCH" in
  X86_64|Aarch64) ;;
  *) die "SCHEMA_ARCH must be X86_64|Aarch64 (got '$SCHEMA_ARCH')" ;;
esac
[ -d "$OUT_DIR" ] || die "OUT_DIR '$OUT_DIR' does not exist (produce_stage5 must create it)"

# CLASSIFICATION SEPARATION: the authoritative genuine-verifier harness must NEVER be
# driven by the off-venue dry-run (TEST_ONLY) mode. The dry-run path synthesizes a
# TEST_ONLY bundle via `emit-test-only-bundle` and never calls produce_stage5; if this
# harness is reached with the dry-run flag set, that is a contract violation. Refusing
# here guarantees no synthetic/TEST_ONLY execution can mint Stage-5 mutation evidence.
if is_dryrun; then
  die "verifier-fixture harness must not run in SUMCHAIN_B0PRE_DRYRUN (TEST_ONLY) mode; synthetic evidence can never reach authoritative Stage-5 ingestion"
fi

# ARCHITECTURE RULE (docs/b0-pre/venue/VENUE.md §2): RISC Zero Groth16 verification runs natively on
# x86_64 only — never under emulation or on aarch64.
if [ "$CAND_LC" = "risc0" ]; then
  [ "$SCHEMA_ARCH" = "X86_64" ] || die "RISC Zero Stage-5 verification is x86_64-only (docs/b0-pre/venue/VENUE.md §2); refused for $SCHEMA_ARCH"
  require_native_arch x86_64
fi

# Required host commands. Absent tooling fails closed (no synthetic substitute).
require_cmd docker
require_cmd python3
require_cmd b3sum

# The work dir (parent of OUT_DIR) holds the sibling produce_stage5 artifacts: the
# extractor's verifier-material manifest and the bound prover tool identity.
WORK_DIR="$(cd "$(dirname "$OUT_DIR")" && pwd)"

# The GENUINE terminal-proof/receipt fixture. By DEFAULT it is GENERATED by PROVING the
# frozen candidate guest with the pinned prover toolchain (prove_fixture.sh, provider-
# neutral). An externally-supplied genuine fixture (SP1_G16_FIXTURE / RISC0_G16_FIXTURE,
# e.g. from an authorized partner venue) OVERRIDES generation. Either way it is a
# self-labeled non-selection bundle; a synthetic fixture is NEVER substituted —
# generation fails closed unless the pinned toolchain/container prove the official
# guest, and the proved fixture stays NON_SELECTION / NOT_AN_OFFICIAL_GUEST (no
# venue-built guest identity enters the normative artifact).
case "$CAND_LC" in
  sp1)   FIXTURE_ENV="SP1_G16_FIXTURE";   CAND=Sp1 ;;
  risc0) FIXTURE_ENV="RISC0_G16_FIXTURE"; CAND=Risc0 ;;
esac
FIXTURE_PATH="$(printf '%s' "${!FIXTURE_ENV:-}")"
if [ -n "$FIXTURE_PATH" ]; then
  [ -f "$FIXTURE_PATH" ] || nyr "$FIXTURE_ENV points to '$FIXTURE_PATH', which is not a readable file"
  note "using externally-supplied genuine $CAND_LC fixture: $FIXTURE_PATH"
else
  FIXTURE_PATH="$OUT_DIR/generated-fixture.json"
  VERIFIER_REF="$VERIFIER_REF" CMD_LOG="$CMD_LOG" SCHEMA_ARCH="$SCHEMA_ARCH" \
    TOOL_BINDING="$WORK_DIR/$CAND.tool-binding.json" \
    PROVER_GUEST_INPUT="${PROVER_GUEST_INPUT:-}" \
    bash "$HERE/prove_fixture.sh" "$CAND_LC" "$ARCH" "$FIXTURE_PATH" \
    || die "genuine $CAND_LC fixture generation failed closed (no official guest source / pinned toolchain / bound prover identity); no synthetic fixture is substituted"
fi
FIXTURE_ABS="$(cd "$(dirname "$FIXTURE_PATH")" && pwd)/$(basename "$FIXTURE_PATH")"

# The fixture MUST be self-labeled non-selection (all four stamps). A fixture that is
# not so labeled could be mistaken for official evidence and is refused fail-closed.
python3 - "$FIXTURE_ABS" "$REQUIRED_STAMPS" <<'PY' || die "genuine $CAND_LC fixture is missing a required non-selection stamp (all four incl. NOT_AN_OFFICIAL_GUEST are mandatory) or is malformed"
import json, sys
path, required = sys.argv[1], set(json.loads(sys.argv[2]))
try:
    doc = json.load(open(path))
except Exception as e:
    sys.exit(f"fixture is not valid JSON: {e}")
stamps = set(doc.get("stamp") or [])
missing = required - stamps
sys.exit(0 if not missing else f"fixture missing stamps: {sorted(missing)}")
PY

# The verifier-material manifest (VerifierMaterialManifestV1) the extractor produced for
# THIS candidate/arch — its canonical identity is bound into the command log so the
# Stage-5 record is tied to the exact material the sealed bundle also carries. Defaults
# to the sibling extractor output produce_stage5 wrote into the work dir ($WORK_DIR
# was resolved above).
MATERIAL="${VERIFIER_MATERIAL:-$WORK_DIR/$CAND_LC-verifier-material.json}"
[ -f "$MATERIAL" ] || die "verifier-material manifest '$MATERIAL' not found; Stage-4/5 extraction must precede Stage-5 (no material identity to bind)"
MAT_ID="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["manifest_identity_blake3"])' "$MATERIAL")" \
  || die "cannot read manifest_identity_blake3 from verifier-material manifest $MATERIAL"

# ---- materialize the GENUINE pinned in-container verifier+mutation runner ----------
# The runner is pinned to the candidate's exact terminal-verifier crate. It reads the
# genuine fixture, verifies the PRISTINE artifact (must accept — a non-reproducing
# verifier exits non-zero, an evidence-backed INELIGIBLE, never partial), writes the
# raw artifacts, then applies EACH of the five required mutations and records the
# OBSERVED rejection per case. A wrong venue-confirmed API detail (e.g. codec) fails
# the pristine decode/verify and the whole run exits non-zero — it never fabricates.
RUNNER="$OUT_DIR/_runner"
rm -rf "$RUNNER"
mkdir -p "$RUNNER/src"

if [ "$CAND_LC" = "sp1" ]; then
  cat > "$RUNNER/Cargo.toml" <<'TOML'
[package]
name = "b0-pre-sp1-stage5-runner"
version = "0.0.0"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

# Pinned to the SP1 6.3.1 terminal Groth16 verifier. Verification is genuine; no
# outcome is hardcoded. Runs only inside the pinned container venue. The Cargo.lock is
# generated IN-CONTAINER (never shipped unlocked) and its hash is bound before the run.
[dependencies]
sp1-verifier = "=6.3.1"
serde_json = "=1.0.149"
TOML
  cat > "$RUNNER/src/main.rs" <<'RUST'
//! Genuine SP1 6.3.1 Groth16 terminal-verifier + mutation runner (venue-only).
//!
//! Reads a genuine venue-produced fixture (proof / public values / vkey hash),
//! verifies the PRISTINE proof against `sp1_verifier::GROTH16_VK_BYTES` (must
//! succeed), writes the raw artifacts (incl. the consumed verifier material), then
//! derives each mutation's rejection from the ACTUAL verifier result — matching the
//! proven contract in harness/sp1-verifier-material/tests/contract.rs. No outcome is
//! asserted.
use std::fs;
use std::process::ExitCode;

fn hexbytes(s: &str) -> Result<Vec<u8>, String> {
    let s = s.strip_prefix("0x").unwrap_or(s);
    if s.len() % 2 != 0 {
        return Err("odd-length hex".into());
    }
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).map_err(|e| e.to_string()))
        .collect()
}

fn run() -> Result<(), String> {
    let args: Vec<String> = std::env::args().collect();
    let fixture = args.get(1).ok_or("usage: runner <fixture.json> <out_dir>")?;
    let out = args.get(2).ok_or("usage: runner <fixture.json> <out_dir>")?;
    let raw = fs::read(fixture).map_err(|e| format!("read fixture: {e}"))?;
    let f: serde_json::Value = serde_json::from_slice(&raw).map_err(|e| format!("parse fixture: {e}"))?;
    let proof = hexbytes(f["proof_hex"].as_str().ok_or("fixture.proof_hex missing")?)?;
    let public_values = hexbytes(f["public_values_hex"].as_str().ok_or("fixture.public_values_hex missing")?)?;
    let vkey_hash = f["vkey_hash"].as_str().ok_or("fixture.vkey_hash missing")?.to_string();
    let vk: Vec<u8> = sp1_verifier::GROTH16_VK_BYTES.as_ref().to_vec();
    if proof.is_empty() || public_values.is_empty() || vk.is_empty() {
        return Err("INELIGIBLE: empty proof/public-values/vk material".into());
    }

    // Genuine verification of the PRISTINE proof MUST succeed, or the run is an
    // evidence-backed INELIGIBLE (non-zero exit, no output).
    sp1_verifier::Groth16Verifier::verify(&proof, &public_values, &vkey_hash, &vk).map_err(|e| {
        format!("INELIGIBLE: genuine SP1 Groth16 proof did not verify against GROTH16_VK_BYTES: {e:?}")
    })?;

    let w = |name: &str, bytes: &[u8]| -> Result<(), String> {
        fs::write(format!("{out}/{name}"), bytes).map_err(|e| format!("write {name}: {e}"))
    };
    w("terminal-proof.bin", &proof)?;
    w("public-values.bin", &public_values)?;
    w("groth16-vk.bin", &vk)?; // the consumed verifier material
    w("vkey-hash-claim.bin", vkey_hash.as_bytes())?;

    // actual_rejected is DERIVED from the observed verifier result for each mutation.
    let rejected = |p: &[u8], pv: &[u8], vh: &str, k: &[u8]| {
        sp1_verifier::Groth16Verifier::verify(p, pv, vh, k).is_err()
    };
    // flip_public_input_bit
    let mut pv_flip = public_values.clone();
    pv_flip[0] ^= 0x01;
    let flip_public_input_bit = rejected(&proof, &pv_flip, &vkey_hash, &vk);
    // truncate_proof
    let truncate_proof = rejected(&proof[..proof.len() - 1], &public_values, &vkey_hash, &vk);
    // swap_verifier_material — verify against DIFFERENT verifier material (a mutated
    // Groth16 vk); the vk is a genuine verify input, so this is real material substitution.
    let mut vk_swapped = vk.clone();
    vk_swapped[0] ^= 0x01;
    let swap_verifier_material = rejected(&proof, &public_values, &vkey_hash, &vk_swapped);
    // corrupt_terminal_claim (mutate the committed vkey hash)
    let mut vh_bytes = vkey_hash.clone().into_bytes();
    if let Some(c) = vh_bytes.last_mut() {
        *c = if *c == b'0' { b'1' } else { b'0' };
    }
    let vh_corrupt = String::from_utf8_lossy(&vh_bytes).into_owned();
    let corrupt_terminal_claim = rejected(&proof, &public_values, &vh_corrupt, &vk);
    // zero_fill_receipt
    let zero = vec![0u8; proof.len()];
    let zero_fill_receipt = rejected(&zero, &public_values, &vkey_hash, &vk);

    let mutations = serde_json::json!([
        {"name": "flip_public_input_bit",   "actual_rejected": flip_public_input_bit},
        {"name": "truncate_proof",          "actual_rejected": truncate_proof},
        {"name": "swap_verifier_material",  "actual_rejected": swap_verifier_material},
        {"name": "corrupt_terminal_claim",  "actual_rejected": corrupt_terminal_claim},
        {"name": "zero_fill_receipt",       "actual_rejected": zero_fill_receipt},
    ]);
    fs::write(
        format!("{out}/mutations.json"),
        serde_json::to_string_pretty(&mutations).map_err(|e| e.to_string())?,
    )
    .map_err(|e| format!("write mutations.json: {e}"))
}

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("{e}");
            ExitCode::FAILURE
        }
    }
}
RUST
  RAW_ARTIFACTS=(
    "genuine-fixture:genuine-fixture.json"
    "runner-cargo-lock:runner-cargo.lock"
    "terminal-proof:terminal-proof.bin"
    "public-values:public-values.bin"
    "groth16-vk:groth16-vk.bin"
    "vkey-hash-claim:vkey-hash-claim.bin"
  )
else
  cat > "$RUNNER/Cargo.toml" <<'TOML'
[package]
name = "b0-pre-risc0-stage5-runner"
version = "0.0.0"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

# Pinned to RISC Zero 3.0.5. Verification is genuine (Receipt::verify(image_id));
# no outcome is hardcoded. Runs only on a native x86_64 container venue. The
# Cargo.lock is generated IN-CONTAINER (never shipped unlocked) and bound before the run.
[dependencies]
risc0-zkvm = "=3.0.5"
serde_json = "=1.0.149"
bincode = "=1.3.3"
TOML
  cat > "$RUNNER/src/main.rs" <<'RUST'
//! Genuine RISC Zero 3.0.5 Groth16 receipt-verifier + mutation runner (venue-only,
//! native x86_64).
//!
//! Reads a genuine venue-produced fixture (bincode-serialized `Receipt` + image id),
//! verifies the PRISTINE receipt via `Receipt::verify(image_id)` (must succeed),
//! writes the raw artifacts (incl. the consumed Groth16 verifier material), then
//! derives each mutation's rejection from the ACTUAL verifier result — matching the
//! checklist in harness/risc0-verifier-material/tests/contract.rs. The receipt codec
//! and field/API names are venue-confirmed (the crate is present there); a wrong
//! detail fails the pristine decode/verify and the whole run exits non-zero, never
//! fabricating an outcome. No outcome is asserted.
use std::fs;
use std::process::ExitCode;

use risc0_zkvm::sha::Digest;
use risc0_zkvm::{Groth16ReceiptVerifierParameters, Receipt, VerifierContext};

fn hex(b: &[u8]) -> String {
    use std::fmt::Write as _;
    let mut s = String::with_capacity(b.len() * 2);
    for x in b {
        let _ = write!(s, "{x:02x}");
    }
    s
}

fn hexbytes(s: &str) -> Result<Vec<u8>, String> {
    let s = s.strip_prefix("0x").unwrap_or(s);
    if s.len() % 2 != 0 {
        return Err("odd-length hex".into());
    }
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).map_err(|e| e.to_string()))
        .collect()
}

fn run() -> Result<(), String> {
    let args: Vec<String> = std::env::args().collect();
    let fixture = args.get(1).ok_or("usage: runner <fixture.json> <out_dir>")?;
    let out = args.get(2).ok_or("usage: runner <fixture.json> <out_dir>")?;
    let raw = fs::read(fixture).map_err(|e| format!("read fixture: {e}"))?;
    let f: serde_json::Value = serde_json::from_slice(&raw).map_err(|e| format!("parse fixture: {e}"))?;

    let receipt_bytes = hexbytes(f["receipt_hex"].as_str().ok_or("fixture.receipt_hex missing")?)?;
    let image_id_hex = f["image_id"].as_str().ok_or("fixture.image_id missing")?.to_string();
    if receipt_bytes.is_empty() {
        return Err("INELIGIBLE: empty serialized receipt".into());
    }
    // A wrong venue-confirmed codec fails HERE (fail closed), never fabricates.
    let receipt: Receipt =
        bincode::deserialize(&receipt_bytes).map_err(|e| format!("INELIGIBLE: cannot decode pinned Receipt: {e}"))?;
    let image_id: Digest = image_id_hex.parse().map_err(|e| format!("bad image_id hex: {e:?}"))?;
    if receipt.journal.bytes.is_empty() {
        return Err("INELIGIBLE: empty journal (no public output)".into());
    }

    // Genuine verification of the PRISTINE receipt MUST succeed.
    receipt
        .verify(image_id)
        .map_err(|e| format!("INELIGIBLE: genuine RISC Zero Groth16 receipt did not verify: {e:?}"))?;

    // The immutable Groth16 verifier material actually consumed by the verify path.
    let params = Groth16ReceiptVerifierParameters::default();
    let vk_bytes = params.verifying_key.to_bytes();
    let control_root_bytes = params.control_root.as_bytes().to_vec();

    let w = |name: &str, bytes: &[u8]| -> Result<(), String> {
        fs::write(format!("{out}/{name}"), bytes).map_err(|e| format!("write {name}: {e}"))
    };
    w("terminal-receipt.bin", &receipt_bytes)?;
    w("image-id.bin", image_id_hex.as_bytes())?;
    w("journal.bin", &receipt.journal.bytes)?;
    w("groth16-vk.bin", &vk_bytes)?; // consumed verifier material
    w("control-root.bin", &control_root_bytes)?; // consumed verifier material

    // actual_rejected DERIVED from the observed verifier result for each mutation.
    // flip_public_input_bit: corrupt the journal (public output), verify.
    let flip_public_input_bit = {
        let mut r = receipt.clone();
        r.journal.bytes[0] ^= 0x01;
        r.verify(image_id).is_err()
    };
    // corrupt_terminal_claim: verify against a mutated image id (terminal claim).
    let corrupt_terminal_claim = {
        let mut bad = image_id_hex.clone().into_bytes();
        if let Some(c) = bad.last_mut() {
            *c = if *c == b'0' { b'1' } else { b'0' };
        }
        match String::from_utf8_lossy(&bad).parse::<Digest>() {
            Ok(bad_id) => receipt.verify(bad_id).is_err(),
            Err(_) => true, // an unparsable claim is a rejection
        }
    };
    // swap_verifier_material: verify against DIFFERENT verifier material — a mutated
    // Groth16 control root supplied via a VerifierContext (genuine material
    // substitution, NOT receipt corruption).
    let swap_verifier_material = {
        let mut swapped = Groth16ReceiptVerifierParameters::default();
        let mut cr = hex(swapped.control_root.as_bytes()).into_bytes();
        if let Some(c) = cr.last_mut() {
            *c = if *c == b'0' { b'1' } else { b'0' };
        }
        match String::from_utf8_lossy(&cr).parse::<Digest>() {
            Ok(different_root) => {
                swapped.control_root = different_root;
                let ctx = VerifierContext::default().with_groth16_verifier_parameters(swapped);
                receipt.verify_with_context(&ctx, image_id).is_err()
            }
            Err(_) => true,
        }
    };
    // truncate_proof / zero_fill_receipt: a truncated / zeroed serialized receipt must
    // not verify (decode failure or verify failure — both are rejections).
    let reverify_corrupt = |bytes: &[u8]| -> bool {
        match bincode::deserialize::<Receipt>(bytes) {
            Ok(r) => r.verify(image_id).is_err(),
            Err(_) => true,
        }
    };
    let truncate_proof = reverify_corrupt(&receipt_bytes[..receipt_bytes.len() - 1]);
    let zero_fill_receipt = reverify_corrupt(&vec![0u8; receipt_bytes.len()]);

    let mutations = serde_json::json!([
        {"name": "flip_public_input_bit",   "actual_rejected": flip_public_input_bit},
        {"name": "truncate_proof",          "actual_rejected": truncate_proof},
        {"name": "swap_verifier_material",  "actual_rejected": swap_verifier_material},
        {"name": "corrupt_terminal_claim",  "actual_rejected": corrupt_terminal_claim},
        {"name": "zero_fill_receipt",       "actual_rejected": zero_fill_receipt},
    ]);
    fs::write(
        format!("{out}/mutations.json"),
        serde_json::to_string_pretty(&mutations).map_err(|e| e.to_string())?,
    )
    .map_err(|e| format!("write mutations.json: {e}"))
}

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("{e}");
            ExitCode::FAILURE
        }
    }
}
RUST
  RAW_ARTIFACTS=(
    "genuine-fixture:genuine-fixture.json"
    "runner-cargo-lock:runner-cargo.lock"
    "terminal-receipt:terminal-receipt.bin"
    "image-id:image-id.bin"
    "journal:journal.bin"
    "groth16-vk:groth16-vk.bin"
    "control-root:control-root.bin"
  )
fi

# Bind the EXACT genuine fixture bytes into the sealed chain: copy them in so
# stage5-generate hashes them into fixture_hashes (a reviewer sees what was verified).
cp "$FIXTURE_ABS" "$OUT_DIR/genuine-fixture.json"

# ---- PHASE A: generate the runner Cargo.lock IN-CONTAINER, then BIND it ------------
# A fresh package has no lock, so it is generated inside the pinned image with
# `cargo generate-lockfile` (NOT --locked) and exported; its BLAKE3 is recorded before
# any verification runs. The build in PHASE B then runs `--locked` against THIS lock.
GEN_CMD="docker run --rm --pull never -v $OUT_DIR:/out -e CARGO_TARGET_DIR=/tmp/b0pre-stage5-target $VERIFIER_REF bash -lc 'cd /out/_runner && cargo generate-lockfile'"
{
  printf '# Stage-5 genuine verifier+mutation run for %s (%s) inside %s\n' "$CAND_LC" "$SCHEMA_ARCH" "$VERIFIER_REF"
  printf '%s\n' "$GEN_CMD"
} >> "$CMD_LOG"
docker run --rm --pull never \
  -v "$OUT_DIR:/out" \
  -e CARGO_TARGET_DIR=/tmp/b0pre-stage5-target \
  "$VERIFIER_REF" \
  bash -lc 'cd /out/_runner && cargo generate-lockfile' \
  || die "in-container 'cargo generate-lockfile' failed for the $CAND_LC Stage-5 runner (no unlocked build is attempted)"
[ -s "$OUT_DIR/_runner/Cargo.lock" ] || die "runner Cargo.lock was not generated in-container for $CAND_LC"
cp "$OUT_DIR/_runner/Cargo.lock" "$OUT_DIR/runner-cargo.lock"
RUNNER_LOCK_B3="$(blake3_hex_file "$OUT_DIR/runner-cargo.lock")"
{
  printf 'runner-cargo-lock\trunner-cargo.lock\tblake3:%s\n' "$RUNNER_LOCK_B3"
  printf 'verifier-material-manifest-identity\tblake3:%s\n' "$MAT_ID"
} >> "$CMD_LOG"

# ---- PHASE B: run the genuine verifier + mutations with the BOUND lock -------------
# $OUT_DIR is bind-mounted at /out; the genuine fixture is mounted read-only at
# /fixture.json; the cargo target is container-ephemeral so no build scratch pollutes
# the evidence. `--locked` is valid now: PHASE A generated the lock this runs against.
RUN_CMD="docker run --rm --pull never -v $OUT_DIR:/out -v $FIXTURE_ABS:/fixture.json:ro -e CARGO_TARGET_DIR=/tmp/b0pre-stage5-target $VERIFIER_REF bash -lc 'cd /out/_runner && cargo run --quiet --release --locked -- /fixture.json /out'"
printf '%s\n' "$RUN_CMD" >> "$CMD_LOG"
docker run --rm --pull never \
  -v "$OUT_DIR:/out" \
  -v "$FIXTURE_ABS:/fixture.json:ro" \
  -e CARGO_TARGET_DIR=/tmp/b0pre-stage5-target \
  "$VERIFIER_REF" \
  bash -lc 'cd /out/_runner && cargo run --quiet --release --locked -- /fixture.json /out' \
  || die "genuine in-container $CAND_LC verifier fixture run failed closed (verifier did not reproduce, toolchain absent, or a mutation could not be evaluated)"

# The runner MUST have produced mutations.json; missing output is a fail-closed refusal
# (never a fabricated stand-in).
[ -s "$OUT_DIR/mutations.json" ] || die "runner did not emit mutations.json for $CAND_LC"

# ---- build fixtures.json from the exported raw artifacts (host paths) --------------
# Each raw artifact must exist and be non-empty (stage5-generate hashes its bytes and
# refuses a zero-length fixture). BLAKE3 of each is appended to $CMD_LOG as provenance,
# and each is bound BY HASH into the Stage-5 record's fixture_hashes.
FIX_JSON="$OUT_DIR/fixtures.json"
: > "$FIX_JSON.tmp"
printf '# Stage-5 raw-artifact BLAKE3 provenance for %s (%s)\n' "$CAND_LC" "$SCHEMA_ARCH" >> "$CMD_LOG"
for entry in "${RAW_ARTIFACTS[@]}"; do
  label="${entry%%:*}"
  fname="${entry#*:}"
  path="$OUT_DIR/$fname"
  [ -s "$path" ] || die "runner did not emit non-empty raw artifact '$fname' for $CAND_LC"
  b3="$(blake3_hex_file "$path")"
  printf '%s\t%s\tblake3:%s\n' "$label" "$fname" "$b3" >> "$CMD_LOG"
  printf '%s\t%s\n' "$label" "$path" >> "$FIX_JSON.tmp"
done

# Serialize [{label, path}] with python3 (matches Stage5FixtureInput exactly).
python3 - "$FIX_JSON.tmp" "$FIX_JSON" <<'PY' || die "failed to serialize fixtures.json for $CAND_LC"
import json, sys
tmp, out = sys.argv[1], sys.argv[2]
rows = []
with open(tmp) as fh:
    for line in fh:
        line = line.rstrip("\n")
        if not line:
            continue
        label, path = line.split("\t", 1)
        rows.append({"label": label, "path": path})
json.dump(rows, open(out, "w"), indent=2)
PY
rm -f "$FIX_JSON.tmp"

note "Stage-5 genuine verifier fixture run complete for $CAND_LC ($SCHEMA_ARCH): $(python3 -c 'import json,sys;print(len(json.load(open(sys.argv[1]))))' "$FIX_JSON") raw artifact(s) bound, $(python3 -c 'import json,sys;print(len(json.load(open(sys.argv[1]))))' "$OUT_DIR/mutations.json") mutation case(s) -> stage5-generate derives overall_pass"
